name: Workers_Scale
inputs:
  WORKER_TAG:
    type: TEXT
    name: Worker tag
    info: Leave empty for untagged workers
  WORKER_SLOTS:
    type: TEXT
    name: Number of slots per worker
    default: "2"
    info: Leave empty to calculate value from license
  MAX_WORKERS:
    type: TEXT
    name: Maximum number of workers
  MIN_FREE_SLOTS:
    type: TEXT
    name: Minimum number of free slots
    default: "1"
docker_image_name: buddy/workers-scale
docker_image_tag: latest
working_directory: /buddy
execute_commands:
  - . calc.sh
output:
  variables:
    WORKERS:
      example: "2"
      info: Number of workers
    WORKER_SLOTS:
      example: "4"
    WORKER_TAG:
      example: "TAG"
